# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='band_name',
            new_name='band',
        ),
    ]
