# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_auto_20170420_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='band_amount',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='concert',
            name='band_name',
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
    ]
