# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_auto_20170422_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
        migrations.AddField(
            model_name='concert',
            name='ticket_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
